# Generated by Django 5.0 on 2023-12-30 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_remove_sample_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('sent', models.DateTimeField(auto_now_add=True)),
                ('is_checked', models.BooleanField(default=False)),
            ],
        ),
    ]
