# Generated by Django 3.2.6 on 2023-12-05 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_auto_20231204_1757'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='surname',
        ),
        migrations.AddField(
            model_name='car',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Ulanyjylar'),
        ),
        migrations.AddField(
            model_name='car',
            name='vehicle_number',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='documents',
            field=models.FileField(null=True, upload_to='user/documents'),
        ),
        migrations.AddField(
            model_name='user',
            name='father_name',
            field=models.CharField(default=1, max_length=40, verbose_name='Atasynyň ady'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='passport_serie',
            field=models.CharField(default=1, max_length=20, verbose_name='Pasport nomeri'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='', max_length=10, verbose_name='Telefon nomeri'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='E-Mail'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=200, unique=True, verbose_name='Ulanyjy ady'),
        ),
        migrations.AddField(
            model_name='car',
            name='car_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='MyApp.year'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='MyApp.color'),
            preserve_default=False,
        ),
    ]
