# Generated by Django 3.2.6 on 2023-12-06 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_auto_20231205_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='car_id',
        ),
        migrations.AlterField(
            model_name='car',
            name='car_desc',
            field=models.TextField(default=''),
        ),
    ]
