# Generated by Django 3.2.6 on 2023-12-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_auto_20231206_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='documents',
            field=models.FileField(blank=True, null=True, upload_to='user/documents'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-Mail'),
        ),
    ]
