# Generated by Django 3.2.6 on 2023-12-06 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0005_auto_20231206_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(default='', upload_to='car/images/'),
        ),
        migrations.AddField(
            model_name='car',
            name='vehicle_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='MyApp.vehicletype'),
            preserve_default=False,
        ),
    ]
