# Generated by Django 3.2.6 on 2023-12-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0006_auto_20231206_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='characteristics_docx',
            field=models.FileField(blank=True, null=True, upload_to='car/characteristics/docx/'),
        ),
        migrations.AddField(
            model_name='car',
            name='characteristics_pdf',
            field=models.FileField(blank=True, null=True, upload_to='car/characteristics/pdf/'),
        ),
    ]
